/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminAduserRouteImport } from './routes/admin/aduser'
import { Route as AdminAdpageRouteImport } from './routes/admin/adpage'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AdminAdpageEditIdRouteImport } from './routes/admin/adpage-edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAduserRoute = AdminAduserRouteImport.update({
  id: '/aduser',
  path: '/aduser',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdpageRoute = AdminAdpageRouteImport.update({
  id: '/adpage',
  path: '/adpage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdpageEditIdRoute = AdminAdpageEditIdRouteImport.update({
  id: '/adpage-edit/$id',
  path: '/adpage-edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/aduser': typeof AdminAduserRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/aduser': typeof AdminAduserRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/aduser': typeof AdminAduserRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/aduser'
    | '/api/$'
    | '/auth/$pathname'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/admin/adpage-edit/$id'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/aduser'
    | '/api/$'
    | '/auth/$pathname'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/admin/adpage-edit/$id'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/aduser'
    | '/api/$'
    | '/auth/$pathname'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/admin/adpage-edit/$id'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountPathnameRoute: typeof AccountPathnameRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aduser': {
      id: '/admin/aduser'
      path: '/aduser'
      fullPath: '/admin/aduser'
      preLoaderRoute: typeof AdminAduserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adpage': {
      id: '/admin/adpage'
      path: '/adpage'
      fullPath: '/admin/adpage'
      preLoaderRoute: typeof AdminAdpageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adpage-edit/$id': {
      id: '/admin/adpage-edit/$id'
      path: '/adpage-edit/$id'
      fullPath: '/admin/adpage-edit/$id'
      preLoaderRoute: typeof AdminAdpageEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdpageRoute: typeof AdminAdpageRoute
  AdminAduserRoute: typeof AdminAduserRoute
  AdminAdpageEditIdRoute: typeof AdminAdpageEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdpageRoute: AdminAdpageRoute,
  AdminAduserRoute: AdminAduserRoute,
  AdminAdpageEditIdRoute: AdminAdpageEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountPathnameRoute: AccountPathnameRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
