/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdpagePageidRouteImport } from './routes/adpage/$pageid'
import { Route as AdminAdsalerRouteImport } from './routes/admin/adsaler'
import { Route as AdminAdpageRouteImport } from './routes/admin/adpage'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AdminImagesPageRouteImport } from './routes/admin/images.$page'
import { Route as AdminAdpageEditIdRouteImport } from './routes/admin/adpage-edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdpagePageidRoute = AdpagePageidRouteImport.update({
  id: '/adpage/$pageid',
  path: '/adpage/$pageid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsalerRoute = AdminAdsalerRouteImport.update({
  id: '/adsaler',
  path: '/adsaler',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdpageRoute = AdminAdpageRouteImport.update({
  id: '/adpage',
  path: '/adpage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagesPageRoute = AdminImagesPageRouteImport.update({
  id: '/images/$page',
  path: '/images/$page',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdpageEditIdRoute = AdminAdpageEditIdRouteImport.update({
  id: '/adpage-edit/$id',
  path: '/adpage-edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/adsaler': typeof AdminAdsalerRoute
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/admin/images/$page': typeof AdminImagesPageRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/adsaler': typeof AdminAdsalerRoute
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/admin/images/$page': typeof AdminImagesPageRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/adpage': typeof AdminAdpageRoute
  '/admin/adsaler': typeof AdminAdsalerRoute
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/admin/adpage-edit/$id': typeof AdminAdpageEditIdRoute
  '/admin/images/$page': typeof AdminImagesPageRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/adsaler'
    | '/adpage/$pageid'
    | '/api/$'
    | '/auth/$pathname'
    | '/admin/adpage-edit/$id'
    | '/admin/images/$page'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/adsaler'
    | '/adpage/$pageid'
    | '/api/$'
    | '/auth/$pathname'
    | '/admin/adpage-edit/$id'
    | '/admin/images/$page'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/adsaler'
    | '/adpage/$pageid'
    | '/api/$'
    | '/auth/$pathname'
    | '/admin/adpage-edit/$id'
    | '/admin/images/$page'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountPathnameRoute: typeof AccountPathnameRoute
  AdpagePageidRoute: typeof AdpagePageidRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adpage/$pageid': {
      id: '/adpage/$pageid'
      path: '/adpage/$pageid'
      fullPath: '/adpage/$pageid'
      preLoaderRoute: typeof AdpagePageidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adsaler': {
      id: '/admin/adsaler'
      path: '/adsaler'
      fullPath: '/admin/adsaler'
      preLoaderRoute: typeof AdminAdsalerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adpage': {
      id: '/admin/adpage'
      path: '/adpage'
      fullPath: '/admin/adpage'
      preLoaderRoute: typeof AdminAdpageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/images/$page': {
      id: '/admin/images/$page'
      path: '/images/$page'
      fullPath: '/admin/images/$page'
      preLoaderRoute: typeof AdminImagesPageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adpage-edit/$id': {
      id: '/admin/adpage-edit/$id'
      path: '/adpage-edit/$id'
      fullPath: '/admin/adpage-edit/$id'
      preLoaderRoute: typeof AdminAdpageEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdpageRoute: typeof AdminAdpageRoute
  AdminAdsalerRoute: typeof AdminAdsalerRoute
  AdminAdpageEditIdRoute: typeof AdminAdpageEditIdRoute
  AdminImagesPageRoute: typeof AdminImagesPageRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdpageRoute: AdminAdpageRoute,
  AdminAdsalerRoute: AdminAdsalerRoute,
  AdminAdpageEditIdRoute: AdminAdpageEditIdRoute,
  AdminImagesPageRoute: AdminImagesPageRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountPathnameRoute: AccountPathnameRoute,
  AdpagePageidRoute: AdpagePageidRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
