/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdpagePageidRouteImport } from './routes/adpage/$pageid'
import { Route as AuthLayoutAdminRouteRouteImport } from './routes/_authLayout/admin/route'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AuthLayoutAuthPathnameRouteImport } from './routes/_authLayout/auth.$pathname'
import { Route as AuthLayoutAdminAdsalerRouteImport } from './routes/_authLayout/admin/adsaler'
import { Route as AuthLayoutAdminAdpageRouteImport } from './routes/_authLayout/admin/adpage'
import { Route as AuthLayoutAccountPathnameRouteImport } from './routes/_authLayout/account.$pathname'
import { Route as AuthLayoutAdminImagesPageRouteImport } from './routes/_authLayout/admin/images.$page'
import { Route as AuthLayoutAdminAdsalerEditIdRouteImport } from './routes/_authLayout/admin/adsaler-edit.$id'
import { Route as AuthLayoutAdminAdpageEditIdRouteImport } from './routes/_authLayout/admin/adpage-edit.$id'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdpagePageidRoute = AdpagePageidRouteImport.update({
  id: '/adpage/$pageid',
  path: '/adpage/$pageid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutAdminRouteRoute = AuthLayoutAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutAuthPathnameRoute = AuthLayoutAuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminAdsalerRoute = AuthLayoutAdminAdsalerRouteImport.update({
  id: '/adsaler',
  path: '/adsaler',
  getParentRoute: () => AuthLayoutAdminRouteRoute,
} as any)
const AuthLayoutAdminAdpageRoute = AuthLayoutAdminAdpageRouteImport.update({
  id: '/adpage',
  path: '/adpage',
  getParentRoute: () => AuthLayoutAdminRouteRoute,
} as any)
const AuthLayoutAccountPathnameRoute =
  AuthLayoutAccountPathnameRouteImport.update({
    id: '/account/$pathname',
    path: '/account/$pathname',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminImagesPageRoute =
  AuthLayoutAdminImagesPageRouteImport.update({
    id: '/images/$page',
    path: '/images/$page',
    getParentRoute: () => AuthLayoutAdminRouteRoute,
  } as any)
const AuthLayoutAdminAdsalerEditIdRoute =
  AuthLayoutAdminAdsalerEditIdRouteImport.update({
    id: '/adsaler-edit/$id',
    path: '/adsaler-edit/$id',
    getParentRoute: () => AuthLayoutAdminRouteRoute,
  } as any)
const AuthLayoutAdminAdpageEditIdRoute =
  AuthLayoutAdminAdpageEditIdRouteImport.update({
    id: '/adpage-edit/$id',
    path: '/adpage-edit/$id',
    getParentRoute: () => AuthLayoutAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthLayoutAdminRouteRouteWithChildren
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/account/$pathname': typeof AuthLayoutAccountPathnameRoute
  '/admin/adpage': typeof AuthLayoutAdminAdpageRoute
  '/admin/adsaler': typeof AuthLayoutAdminAdsalerRoute
  '/auth/$pathname': typeof AuthLayoutAuthPathnameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/adpage-edit/$id': typeof AuthLayoutAdminAdpageEditIdRoute
  '/admin/adsaler-edit/$id': typeof AuthLayoutAdminAdsalerEditIdRoute
  '/admin/images/$page': typeof AuthLayoutAdminImagesPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthLayoutAdminRouteRouteWithChildren
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/account/$pathname': typeof AuthLayoutAccountPathnameRoute
  '/admin/adpage': typeof AuthLayoutAdminAdpageRoute
  '/admin/adsaler': typeof AuthLayoutAdminAdsalerRoute
  '/auth/$pathname': typeof AuthLayoutAuthPathnameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/adpage-edit/$id': typeof AuthLayoutAdminAdpageEditIdRoute
  '/admin/adsaler-edit/$id': typeof AuthLayoutAdminAdsalerEditIdRoute
  '/admin/images/$page': typeof AuthLayoutAdminImagesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_authLayout/admin': typeof AuthLayoutAdminRouteRouteWithChildren
  '/adpage/$pageid': typeof AdpagePageidRoute
  '/api/$': typeof ApiSplatRoute
  '/_authLayout/account/$pathname': typeof AuthLayoutAccountPathnameRoute
  '/_authLayout/admin/adpage': typeof AuthLayoutAdminAdpageRoute
  '/_authLayout/admin/adsaler': typeof AuthLayoutAdminAdsalerRoute
  '/_authLayout/auth/$pathname': typeof AuthLayoutAuthPathnameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_authLayout/admin/adpage-edit/$id': typeof AuthLayoutAdminAdpageEditIdRoute
  '/_authLayout/admin/adsaler-edit/$id': typeof AuthLayoutAdminAdsalerEditIdRoute
  '/_authLayout/admin/images/$page': typeof AuthLayoutAdminImagesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adpage/$pageid'
    | '/api/$'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/adsaler'
    | '/auth/$pathname'
    | '/api/rpc/$'
    | '/admin/adpage-edit/$id'
    | '/admin/adsaler-edit/$id'
    | '/admin/images/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adpage/$pageid'
    | '/api/$'
    | '/account/$pathname'
    | '/admin/adpage'
    | '/admin/adsaler'
    | '/auth/$pathname'
    | '/api/rpc/$'
    | '/admin/adpage-edit/$id'
    | '/admin/adsaler-edit/$id'
    | '/admin/images/$page'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_authLayout/admin'
    | '/adpage/$pageid'
    | '/api/$'
    | '/_authLayout/account/$pathname'
    | '/_authLayout/admin/adpage'
    | '/_authLayout/admin/adsaler'
    | '/_authLayout/auth/$pathname'
    | '/api/rpc/$'
    | '/_authLayout/admin/adpage-edit/$id'
    | '/_authLayout/admin/adsaler-edit/$id'
    | '/_authLayout/admin/images/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AdpagePageidRoute: typeof AdpagePageidRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adpage/$pageid': {
      id: '/adpage/$pageid'
      path: '/adpage/$pageid'
      fullPath: '/adpage/$pageid'
      preLoaderRoute: typeof AdpagePageidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/admin': {
      id: '/_authLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthLayoutAdminRouteRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/auth/$pathname': {
      id: '/_authLayout/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthLayoutAuthPathnameRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/admin/adsaler': {
      id: '/_authLayout/admin/adsaler'
      path: '/adsaler'
      fullPath: '/admin/adsaler'
      preLoaderRoute: typeof AuthLayoutAdminAdsalerRouteImport
      parentRoute: typeof AuthLayoutAdminRouteRoute
    }
    '/_authLayout/admin/adpage': {
      id: '/_authLayout/admin/adpage'
      path: '/adpage'
      fullPath: '/admin/adpage'
      preLoaderRoute: typeof AuthLayoutAdminAdpageRouteImport
      parentRoute: typeof AuthLayoutAdminRouteRoute
    }
    '/_authLayout/account/$pathname': {
      id: '/_authLayout/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AuthLayoutAccountPathnameRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/admin/images/$page': {
      id: '/_authLayout/admin/images/$page'
      path: '/images/$page'
      fullPath: '/admin/images/$page'
      preLoaderRoute: typeof AuthLayoutAdminImagesPageRouteImport
      parentRoute: typeof AuthLayoutAdminRouteRoute
    }
    '/_authLayout/admin/adsaler-edit/$id': {
      id: '/_authLayout/admin/adsaler-edit/$id'
      path: '/adsaler-edit/$id'
      fullPath: '/admin/adsaler-edit/$id'
      preLoaderRoute: typeof AuthLayoutAdminAdsalerEditIdRouteImport
      parentRoute: typeof AuthLayoutAdminRouteRoute
    }
    '/_authLayout/admin/adpage-edit/$id': {
      id: '/_authLayout/admin/adpage-edit/$id'
      path: '/adpage-edit/$id'
      fullPath: '/admin/adpage-edit/$id'
      preLoaderRoute: typeof AuthLayoutAdminAdpageEditIdRouteImport
      parentRoute: typeof AuthLayoutAdminRouteRoute
    }
  }
}

interface AuthLayoutAdminRouteRouteChildren {
  AuthLayoutAdminAdpageRoute: typeof AuthLayoutAdminAdpageRoute
  AuthLayoutAdminAdsalerRoute: typeof AuthLayoutAdminAdsalerRoute
  AuthLayoutAdminAdpageEditIdRoute: typeof AuthLayoutAdminAdpageEditIdRoute
  AuthLayoutAdminAdsalerEditIdRoute: typeof AuthLayoutAdminAdsalerEditIdRoute
  AuthLayoutAdminImagesPageRoute: typeof AuthLayoutAdminImagesPageRoute
}

const AuthLayoutAdminRouteRouteChildren: AuthLayoutAdminRouteRouteChildren = {
  AuthLayoutAdminAdpageRoute: AuthLayoutAdminAdpageRoute,
  AuthLayoutAdminAdsalerRoute: AuthLayoutAdminAdsalerRoute,
  AuthLayoutAdminAdpageEditIdRoute: AuthLayoutAdminAdpageEditIdRoute,
  AuthLayoutAdminAdsalerEditIdRoute: AuthLayoutAdminAdsalerEditIdRoute,
  AuthLayoutAdminImagesPageRoute: AuthLayoutAdminImagesPageRoute,
}

const AuthLayoutAdminRouteRouteWithChildren =
  AuthLayoutAdminRouteRoute._addFileChildren(AuthLayoutAdminRouteRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutAdminRouteRoute: typeof AuthLayoutAdminRouteRouteWithChildren
  AuthLayoutAccountPathnameRoute: typeof AuthLayoutAccountPathnameRoute
  AuthLayoutAuthPathnameRoute: typeof AuthLayoutAuthPathnameRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAdminRouteRoute: AuthLayoutAdminRouteRouteWithChildren,
  AuthLayoutAccountPathnameRoute: AuthLayoutAccountPathnameRoute,
  AuthLayoutAuthPathnameRoute: AuthLayoutAuthPathnameRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AdpagePageidRoute: AdpagePageidRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
